### ISSUE TITLE
api instructions dosnt work?

### ISSUE THREAD

**Issue by Cowsick** [michaelmcarthur/GoogleGeocode-HASS#37]
get this error

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:599
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:05:00 (4 occurrences)
Last logged: 20:31:31

[281472931109376] The system cannot restart because the configuration is not valid: Platform error sensor.google_geocode - Integration 'google_geocode' not found. Platform error sensor.google_geocode - Integration 'google_geocode' not found.
[281472921613840] The system cannot restart because the configuration is not valid: Platform error sensor.google_geocode - Integration 'google_geocode' not found. Platform error sensor.google_geocode - Integration 'google_geocode' not found.
[281472921825232] The system cannot restart because the configuration is not valid: Platform error sensor.google_geocode - Integration 'google_geocode' not found. Platform error sensor.google_geocode - Integration 'google_geocode' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 599, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.google_geocode - Integration 'google_geocode' not found.
Platform error sensor.google_geocode - Integration 'google_geocode' not found.

____

have created api key.. but the instructions isnt really as the plattform

instructions sas
Go to Google Maps Platform API
Click on 'Get Started'
Select 'Maps' and 'Places' then click 'continue'
Create a new project or select an existing one then click 'next'.
Clcik 'Create Billing Account'
Create a name for the account then click 'Continue'
Confirm your Country then click 'Confirm'
Fill in your detail the click 'Submit and enable billing'
To Emable your API's Click 'Next'
Copy your API key.
__

but there isnt any Maps API?
enabled all these
Geocoding API
Geolocation API
Maps Elevation API
Maps Embed API
Maps JavaScript API
Maps Static API
Places API

But there arnt any request to any of em?

**Comment by axerontios** [comment]
Same here, the instruction might need to get updated. confused over here as well

**Comment by LeeWiu** [comment]
Add version to manifest file, should look like this:
`{
  "domain": "google_geocode",
  "name": "Google Geocode",
  "version":"1.0",
  "documentation": "https://github.com/michaelmcarthur/GoogleGeocode-HASS",
  "dependencies": [],
  "codeowners": [],
  "requirements": []
}`

**Comment by Cowsick** [comment]
> Add version to manifest file, should look like this: `{ "domain": "google_geocode", "name": "Google Geocode", "version":"1.0", "documentation": "https://github.com/michaelmcarthur/GoogleGeocode-HASS", "dependencies": [], "codeowners": [], "requirements": [] }`

all that was already there
